### ISSUE TITLE
Auto reconnect when Jack server is restarted

### ISSUE THREAD

**Issue by mfr-itr** [SpotlightKid/jack-matchmaker#1]
If the Jack server is restarted while matchmaker is running, stdout is flooded with "JackClientSocket::Read time out" messages. It could try to reconnect to the new Jack server.

**Comment by SpotlightKid** [comment]
Thanks for the report. This is something I also noticed already as well. I will try to have a look into a solution soon.

**Comment by mfr-itr** [comment]
Nice! Good application BTW, very handy.

**Comment by SpotlightKid** [comment]
I've added a tentative implementation of the requested feature in commit e512c51 .

`jack-matchmaker` now tries to connect to JACK until a connection can be established or the maximum number of connection (re-)tries is exceeded (new option `-m/--max-tries`, default: 0 == infinite tries) and waits for 3 seconds between each connection attempts (change interval with option `-I/--connect-interval`). When connected and the JACK server is stopped, it signals the shutdown event to `jack-matchmaker`, which goes into the connection loop again.

Can you please test this and give feedback whether this works for you or you have any suggestions for improvement?

**Comment by mfr-itr** [comment]
Seems like a good way to handle it. I'll try at home, ping me in a few days if I didn't respond ;)

**Comment by SpotlightKid** [comment]
I've now released version 0.6.0, which incorporates the changes described above.

**Comment by mfr-itr** [comment]
Sorry, forgot to test...
