### ISSUE TITLE
Only makes a connection if none already exists

### ISSUE THREAD

**Issue by kltdwrds** [SpotlightKid/jack-matchmaker#13]
jack-plumbing works this way - from their docs:
```
(connect "SuperCollider:out_(.*)" "system:playback_\1")
This connect rule ensures that whenever scsynth(1) is running any output ports it registers are connected to appropriate ALSA playback ports. 
The connect rule only makes a connection if none already exist.
```

Cheers!

**Comment by SpotlightKid** [comment]
Sorry for only looking in detail at this request, but now that I do, I am not sure that I understand what you mean. From the description in the `jack-plumbing` docs - and looking at its source code - I think `jack-matchmaker` already works that way. Or what it is exactly that you want it to do, that it does not do yet?

**Comment by SpotlightKid** [comment]
Closing due to norther feedback.

Please feel free to re-open *if* you have additional information to add.
