### ISSUE TITLE
Unable to create systemd service using provided instructions

### ISSUE THREAD

**Issue by ArchOwlen** [SpotlightKid/jack-matchmaker#21]
System: Arch/Manjaro-5.17.1-3
Jack-matchmaker version: 0.10.0-1 (from AUR)

Output of provided commands:
![image](https://user-images.githubusercontent.com/69368336/167732581-a34f6930-8c9f-4adf-8f05-0966c1ef8c97.png)

(same issue when running as sudo)

Issue persists if directory is 'corrected' to /etc/

Issue also persists when files are manually created:
![image](https://user-images.githubusercontent.com/69368336/167732813-71405027-c6dc-496d-a6b3-1235dacb5e19.png)

**Comment by SpotlightKid** [comment]
The install instructions assume that you run them within the root directory of a checkout of the repository or an unpacked sopurce distribution as the current working directory.

The [jack-matchmaker AUR package](https://aur.archlinux.org/packages/jack-matchmaker) already installs these two files. All you need to do is edit `/etc/conf.d/jack-matchmaker` to your liking and enable/start the service as stated in the rest of the instructions.
