### ISSUE TITLE
install issue on Raspbain Buster

### ISSUE THREAD

**Issue by okyeron** [SpotlightKid/jack-matchmaker#4]
Tired to install jack-matchmaker today on Raspberry Pi 4 with Buster installed. Getting some errors.

Any suggestions on how to troubleshoot this?
```
10.0.1.20 ~ $ pip install jack-matchmaker
...

Successfully installed jack-matchmaker-0.7.1

10.0.1.20 ~ $ jack-matchmaker --help
Traceback (most recent call last):
  File "/home/we/.local/bin/jack-matchmaker", line 6, in <module>
    from jackmatchmaker import main
  File "/home/we/.local/lib/python2.7/site-packages/jackmatchmaker/__init__.py", line 245
    num_aliases, *aliases = jacklib.port_get_aliases(port)
                 ^
SyntaxError: invalid syntax

10.0.1.20 ~ $ jackd -V
jackdmp version 1.9.12 tmpdir /dev/shm protocol 8

```

**Comment by SpotlightKid** [comment]
`jack-matchmaker` is not compatible with Python 2.x. Try `pip3 install ...`. You might need to install `python3` and `python3-pip` system packages first (not sure what the default Python version is on your distro).

**Comment by okyeron** [comment]
Awesome. Thanks for that. Python 2.7.16 here so that makes sense.

Apologies as I completely missed the requirements section.
